name: My First Workflow

on:
  push: 

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Welcome to GitHub Actions"
          echo "This is Day 2"
          echo "Learning CI/CD step by step"
      