name: Runner Demo

on:
  push:

jobs:
  runner-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Show Current Directory
        run: pwd

      - name: Show Current User
        run: whoami

      - name: Show Operating System
        run: uname -a

      - name: Show Files
        run: ls -la