name: secrets test

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      MY_APP: ${{ secrets.APP_NAME }}
      message: ${{ secrets.WELCOME_MESSAGE }}
    steps:
      - name: access secrets
        run: echo "my app name is $MY_APP and the message is $message"