name: test vm 

on:
  workflow_dispatch:

env:
  server_ip: 172.20.10.4
  server_username: salman
  VM_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
jobs:
  test-vm:
    runs-on: ubuntu-latest
    steps:
      - name: connect to vm
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ env.server_ip }}
          username: ${{ env.server_username }}
          key: ${{ env.VM_PRIVATE_KEY }}
          script: |
            echo "Connected to VM successfully"
            mkdir -p /home/salman/test_directory
            echo "Test directory created"
    